# Generated by Django 4.2.28 on 2026-02-27 21:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL-путь')),
                ('description', mdeditor.fields.MDTextField(blank=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('format', models.CharField(choices=[('offline', 'Офлайн'), ('online', 'Онлайн'), ('hybrid', 'Гибрид')], default='offline', max_length=20, verbose_name='Формат')),
                ('location_address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('location_city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('location_venue', models.CharField(blank=True, max_length=200, verbose_name='Помещение/зал')),
                ('online_url', models.URLField(blank=True, verbose_name='Ссылка на трансляцию')),
                ('online_platform', models.CharField(blank=True, max_length=100, verbose_name='Платформа (Zoom и т.п.)')),
                ('event_type', models.CharField(choices=[('meetup', 'Митап'), ('workshop', 'Воркшоп'), ('conference', 'Конференция'), ('networking', 'Нетворкинг')], default='meetup', max_length=20, verbose_name='Тип события')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Обложка')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Лимит участников')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Цена участия')),
                ('registration_type', models.CharField(choices=[('open', 'Открытая'), ('requires_approval', 'Требует подтверждения'), ('closed', 'Закрытая')], default='open', max_length=20, verbose_name='Тип регистрации')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('registration_closed', 'Регистрация закрыта'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='draft', max_length=30, verbose_name='Статус')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO: заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='SEO: описание')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать в «Ваш выбор»')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-date', '-time_start'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL-путь')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория событий',
                'verbose_name_plural': 'Категории событий',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название галереи')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='galleries/', verbose_name='Обложка')),
                ('photo_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во фото')),
                ('external_album_url', models.URLField(blank=True, verbose_name='Ссылка на альбом (VK и т.п.)')),
            ],
            options={
                'verbose_name': 'Галерея события',
                'verbose_name_plural': 'Галереи событий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/', verbose_name='Фотография')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='Ссылки на соцсети')),
                ('topics', models.ManyToManyField(blank=True, related_name='speakers', to='core.tag', verbose_name='Темы выступлений')),
            ],
            options={
                'verbose_name': 'Спикер',
                'verbose_name_plural': 'Спикеры',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EventSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название сегмента')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('time_end', models.TimeField(verbose_name='Время окончания')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='events.event', verbose_name='Событие')),
                ('speakers', models.ManyToManyField(blank=True, related_name='event_segments', to='events.speaker', verbose_name='Спикеры')),
            ],
            options={
                'verbose_name': 'Сегмент программы',
                'verbose_name_plural': 'Сегменты программы',
                'ordering': ['event', 'order', 'time_start'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('attendance_status', models.CharField(choices=[('unknown', 'Неизвестно'), ('attended', 'Посетил'), ('no_show', 'Не явился')], default='unknown', max_length=20, verbose_name='Посещение')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Доп. поля формы')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Регистрация на событие',
                'verbose_name_plural': 'Регистрации на события',
                'ordering': ['-created_at'],
            },
        ),
    ]
