# Generated by Django 6.0.2 on 2026-03-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_trgm_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_event_title_trgm',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_event_desc_trgm',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_event_city_trgm',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_event_venue_trgm',
        ),
        migrations.RemoveIndex(
            model_name='speaker',
            name='events_speaker_name_trgm',
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('offline', 'Офлайн'), ('online', 'Онлайн')], default='offline', max_length=20, verbose_name='Формат'),
        ),
    ]
