# Generated by Django 6.0.2 on 2026-03-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_events_event_title_trgm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=True, verbose_name='Показывать в «Ваш выбор»'),
        ),
    ]
