# Generated by Django 6.0.2 on 2026-03-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_eventtheme_and_event_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, help_text='Текст для карточек и списков', max_length=500, verbose_name='Краткое описание (превью)'),
        ),
    ]
