# Generated by Django 4.2.28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=320, unique=True, verbose_name='URL-путь')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание (для карточки)')),
                ('content', mdeditor.fields.MDTextField(blank=True, verbose_name='Содержимое')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Обложка')),
                ('publication_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('read_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Время чтения (мин)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO: заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='SEO: описание')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tags', models.ManyToManyField(blank=True, related_name='news_articles', to='core.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
    ]
