# Generated by Django 6.0.2 on 2026-03-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_trgm_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='newsarticle',
            name='news_article_title_trgm',
        ),
        migrations.RemoveIndex(
            model_name='newsarticle',
            name='news_article_short_trgm',
        ),
        migrations.RemoveIndex(
            model_name='newsarticle',
            name='news_article_content_trgm',
        ),
    ]
