# Generated by Django 4.2.28 on 2026-03-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='material',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность, минут'),
        ),
        migrations.AddField(
            model_name='material',
            name='label',
            field=models.CharField(blank=True, help_text='Текст в верхней строке карточки: КУРС, ЗАПИСЬ, ХЕНДБУК, ФОТОГРАФИИ', max_length=50, null=True, verbose_name='Тип/лейбл'),
        ),
        migrations.AddField(
            model_name='material',
            name='place',
            field=models.CharField(blank=True, help_text='Например: Минск или Online', max_length=100, verbose_name='Место/формат'),
        ),
    ]
