# Generated by Django 6.0.2 on 2026-03-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_trgm_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='material',
            name='materials_title_trgm',
        ),
        migrations.RemoveIndex(
            model_name='material',
            name='materials_label_trgm',
        ),
        migrations.RemoveIndex(
            model_name='material',
            name='materials_desc_trgm',
        ),
        migrations.RemoveIndex(
            model_name='material',
            name='materials_place_trgm',
        ),
        migrations.RemoveIndex(
            model_name='materialcategory',
            name='materials_cat_title_trgm',
        ),
    ]
