# Generated by Django 4.2.28 on 2026-02-27 21:27

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('category', models.CharField(choices=[('report', 'Отчёт'), ('course', 'Курс'), ('checklist', 'Чек-лист'), ('recording', 'Запись'), ('case_study', 'Кейс')], default='report', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file_url', models.URLField(blank=True, verbose_name='Ссылка на файл/страницу')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='Превью')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL-путь')),
                ('content', mdeditor.fields.MDTextField(blank=True, verbose_name='Содержимое')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO: заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='SEO: описание')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('website_url', models.URLField(blank=True, verbose_name='Сайт')),
                ('partnership_level', models.CharField(choices=[('general', 'Генеральный'), ('gold', 'Золотой'), ('silver', 'Серебряный')], default='general', max_length=20, verbose_name='Уровень партнёрства')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Контактное лицо')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_review', 'На рассмотрении'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка на партнёрство',
                'verbose_name_plural': 'Заявки на партнёрство',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='PM.Meetup', max_length=100, verbose_name='Название сайта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Логотип')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Иконка')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email для контактов')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='Ссылки на соцсети')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Фотография')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Команда',
                'ordering': ['display_order', 'full_name'],
            },
        ),
    ]
