# Generated by Django 6.0.2 on 2026-03-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_delete_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.AddField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание того, какую задачу выполняет', verbose_name='Описание'),
        ),
    ]
