# Generated by Django 4.2.28 on 2026-03-03 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код типа блока')),
                ('name', models.CharField(max_length=200, verbose_name='Название типа блока')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип блока',
                'verbose_name_plural': 'Типы блоков',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug страницы')),
                ('name', models.CharField(max_length=200, verbose_name='Название страницы')),
            ],
            options={
                'verbose_name': 'Страница (блоки)',
                'verbose_name_plural': 'Страницы (блоки)',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок на странице')),
                ('block_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_blocks', to='pages.blocktype', verbose_name='Тип блока')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pages.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Блок страницы',
                'verbose_name_plural': 'Блоки страниц',
                'ordering': ['page', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('icon', models.CharField(blank=True, help_text='Ключ или путь до иконки, который использует фронтенд', max_length=255, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок внутри блока')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.pageblock', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Элемент блока',
                'verbose_name_plural': 'Элементы блока',
                'ordering': ['block', 'order', 'id'],
            },
        ),
    ]
