# Generated by Django 6.0.2 on 2026-03-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockitem',
            name='url',
            field=models.URLField(blank=True, help_text='Произвольная ссылка (например, на YouTube-видео или внешний ресурс)', verbose_name='Ссылка'),
        ),
    ]
